mail.enabled=true
mail.provider=smtp
mail.from=no-reply@oceanview.local
mail.smtp.host=sandbox.smtp.mailtrap.io
mail.smtp.port=2525
mail.smtp.username=f4e20b40c28409
mail.smtp.password=413bfa950c4ad0
mail.smtp.starttls=true
mail.smtp.auth=true